name: shared_preferences_ohos
description: Ohos implementation of the shared_preferences plugin
repository: https://gitcode.com/openharmony-tpc/flutter_packages/tree/master/packages/shared_preferences/shared_preferences_ohos
issue_tracker: https://gitcode.com/openharmony-tpc/flutter_packages/issues
version: 2.5.3

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      ohos:
        package: io.flutter.plugins.sharedpreferences
        pluginClass: SharedPreferencesPlugin
        dartPluginClass: SharedPreferencesOhos

dependencies:
  flutter:
    sdk: flutter

  shared_preferences_platform_interface: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.9.0
  pigeon: ^9.2.3

topics:
  - persistence
  - shared-preferences
  - storage
