name: audioplayers
resolution: workspace
description: A Flutter plugin to play multiple audio files simultaneously
version: 6.5.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers
publish_to: none

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows
      ohos:
        default_package: audioplayers_ohos

dependencies:
  audioplayers_android: 
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_android
  audioplayers_ohos:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_ohos
  audioplayers_darwin: 
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_darwin
  audioplayers_linux: 
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_linux
  audioplayers_platform_interface: 
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_platform_interface
  audioplayers_web: 
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_web
  audioplayers_windows: 
    git: 
      url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
      path: packages/audioplayers_windows
  file: ^6.1.0
  flutter:
    sdk: flutter
  http: '>=0.13.1 <2.0.0'
  meta: ^1.7.0
  path_provider:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/path_provider/path_provider
  synchronized: ^3.0.0
  uuid: '>=3.0.7 <5.0.0'

dev_dependencies:
  flame_lint: ^1.3.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

topics:
  - audio
  - audio-player
